### ISSUE TITLE
Component not mounting before searching

### ISSUE THREAD

**Issue by excessivecoding** [yemmyharry/HackerNewsApp#1]
Hello Yemi,

I'm creating this issue so we can track bugs or features, in the future, try to create one issue if you have any question on any project and assign me to it. It will make both our lives easier as we would track issue together and be able to discuss it here !

**Comment by excessivecoding** [comment]
I think I found the issue.

First when I tried locally, it seems like it was working so I suppose it has something to do with production vs dev env.

Second when testing on the production, I noticed an error I don't have locally (cf. screenshot below)

<img width="659" alt="Screenshot 2019-12-14 at 14 54 47" src="https://user-images.githubusercontent.com/7261258/70849640-b4bb2700-1e81-11ea-81e6-4d4c27b9709a.png">

If you read carefully, it says that your site was loaded with HTTPS but you requested data from `http://hn.algolia.com/api/v1/search_by_date?tags=story` (notice that you requested on a HTTP URL instead on HTTPS)

When you serve a website through HTTP*S* you have to request other resources (images, data, etc) through the same protocol to ensure it stays secure.

**Comment by excessivecoding** [comment]
I made the pull request, I let you check out if it fixes your issue, if it doesn't or you have any question, feel free to ask here

**Comment by yemmyharry** [comment]
> Hello Yemi,
> 
> I'm creating this issue so we can track bugs or features, in the future, try to create one issue if you have any question on any project and assign me to it. It will make both our lives easier as we would track issue together and be able to discuss it here !

alright
